
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATE DOLAR EQUALS HOUR ID LQUESTION NORMSTRING NUMBER QUOTATION_MARKS RQUESTION TCARNET TCARRERA TCREDITOS TDESCRIPCION TDPI TEDAD TELEMENT TELEMENTS TESTADO TFECHA THORA TITEM TMATERIA TNOMBRE TPASSWORD TTYPEstatement : LQUESTION TELEMENTS RQUESTION elementos LQUESTION DOLAR TELEMENTS RQUESTIONelementos : elementos elemento\n                 | elemento\n    elemento : LQUESTION TELEMENT  tipoElemento RQUESTION items LQUESTION DOLAR TELEMENT RQUESTIONtipoElemento : TTYPE EQUALS NORMSTRING\n    items : items item\n             | item\n    item : LQUESTION TITEM tipeItem EQUALS valueItem DOLAR RQUESTION\n    valueItem : NORMSTRING\n                 | NUMBER\n                 tipeItem : TCARNET\n                | TDPI\n                | TNOMBRE\n                | TCARRERA\n                | TPASSWORD\n                | TCREDITOS\n                | TEDAD\n                | TDESCRIPCION\n                | TMATERIA\n                | TFECHA\n                | THORA\n                | TESTADO\n                '
    
_lr_action_items = {'LQUESTION':([0,4,6,7,10,14,18,19,24,44,46,],[2,5,9,-3,-2,17,23,-7,-6,-4,-8,]),'$end':([1,21,],[0,-1,]),'TELEMENTS':([2,13,],[3,16,]),'RQUESTION':([3,11,16,20,40,45,],[4,14,21,-5,44,46,]),'TELEMENT':([5,9,38,],[8,8,40,]),'TTYPE':([8,],[12,]),'DOLAR':([9,23,41,42,43,],[13,38,45,-9,-10,]),'EQUALS':([12,25,26,27,28,29,30,31,32,33,34,35,36,37,],[15,39,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,]),'NORMSTRING':([15,39,],[20,42,]),'TITEM':([17,23,],[22,22,]),'TCARNET':([22,],[26,]),'TDPI':([22,],[27,]),'TNOMBRE':([22,],[28,]),'TCARRERA':([22,],[29,]),'TPASSWORD':([22,],[30,]),'TCREDITOS':([22,],[31,]),'TEDAD':([22,],[32,]),'TDESCRIPCION':([22,],[33,]),'TMATERIA':([22,],[34,]),'TFECHA':([22,],[35,]),'THORA':([22,],[36,]),'TESTADO':([22,],[37,]),'NUMBER':([39,],[43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'elementos':([4,],[6,]),'elemento':([4,6,],[7,10,]),'tipoElemento':([8,],[11,]),'items':([14,],[18,]),'item':([14,18,],[19,24,]),'tipeItem':([22,],[25,]),'valueItem':([39,],[41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> LQUESTION TELEMENTS RQUESTION elementos LQUESTION DOLAR TELEMENTS RQUESTION','statement',8,'p_statement_group','sintactico.py',7),
  ('elementos -> elementos elemento','elementos',2,'p_elementos_group','sintactico.py',11),
  ('elementos -> elemento','elementos',1,'p_elementos_group','sintactico.py',12),
  ('elemento -> LQUESTION TELEMENT tipoElemento RQUESTION items LQUESTION DOLAR TELEMENT RQUESTION','elemento',9,'p_elemento','sintactico.py',16),
  ('tipoElemento -> TTYPE EQUALS NORMSTRING','tipoElemento',3,'p_tipoElemento','sintactico.py',19),
  ('items -> items item','items',2,'p_items','sintactico.py',23),
  ('items -> item','items',1,'p_items','sintactico.py',24),
  ('item -> LQUESTION TITEM tipeItem EQUALS valueItem DOLAR RQUESTION','item',7,'p_item','sintactico.py',28),
  ('valueItem -> NORMSTRING','valueItem',1,'p_valueItem','sintactico.py',32),
  ('valueItem -> NUMBER','valueItem',1,'p_valueItem','sintactico.py',33),
  ('tipeItem -> TCARNET','tipeItem',1,'p_tipeItem','sintactico.py',37),
  ('tipeItem -> TDPI','tipeItem',1,'p_tipeItem','sintactico.py',38),
  ('tipeItem -> TNOMBRE','tipeItem',1,'p_tipeItem','sintactico.py',39),
  ('tipeItem -> TCARRERA','tipeItem',1,'p_tipeItem','sintactico.py',40),
  ('tipeItem -> TPASSWORD','tipeItem',1,'p_tipeItem','sintactico.py',41),
  ('tipeItem -> TCREDITOS','tipeItem',1,'p_tipeItem','sintactico.py',42),
  ('tipeItem -> TEDAD','tipeItem',1,'p_tipeItem','sintactico.py',43),
  ('tipeItem -> TDESCRIPCION','tipeItem',1,'p_tipeItem','sintactico.py',44),
  ('tipeItem -> TMATERIA','tipeItem',1,'p_tipeItem','sintactico.py',45),
  ('tipeItem -> TFECHA','tipeItem',1,'p_tipeItem','sintactico.py',46),
  ('tipeItem -> THORA','tipeItem',1,'p_tipeItem','sintactico.py',47),
  ('tipeItem -> TESTADO','tipeItem',1,'p_tipeItem','sintactico.py',48),
]
